#!/usr/bin/env python3
"""
NUI Resource Embedder
Converts files from a directory into C++ byte arrays.
Generates embedded_resources.h and embedded_resources.cpp.

Usage:
    python tools/embed_resources.py <resource_dir> <output_dir>

Example:
    python tools/embed_resources.py resources/ src/generated/
"""

import os
import sys
import hashlib

HEADER = """\
// AUTO-GENERATED by tools/embed_resources.py — DO NOT EDIT
#pragma once
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <unordered_map>

namespace nui {

struct EmbeddedResource {
    const uint8_t* data;
    size_t size;
};

// Look up an embedded resource by virtual path (e.g. "resources/images/cover.png")
// Returns nullptr if not found.
const EmbeddedResource* GetEmbeddedResource(std::string_view path);

// Register all embedded resources (called once at startup)
void RegisterEmbeddedResources();

} // namespace nui
"""

CPP_HEADER = """\
// AUTO-GENERATED by tools/embed_resources.py — DO NOT EDIT
#include "generated/embedded_resources.h"

namespace nui {

static std::unordered_map<std::string_view, EmbeddedResource> s_resources;
static bool s_registered = false;

"""

CPP_FOOTER = """
void RegisterEmbeddedResources() {
    if (s_registered) return;
    s_registered = true;
"""

CPP_FOOTER2 = """\
}

const EmbeddedResource* GetEmbeddedResource(std::string_view path) {
    if (!s_registered) RegisterEmbeddedResources();
    auto it = s_resources.find(path);
    return (it != s_resources.end()) ? &it->second : nullptr;
}

} // namespace nui
"""


def make_var_name(filepath: str) -> str:
    """Convert a file path to a valid C++ variable name."""
    name = filepath.replace("/", "_").replace("\\", "_").replace(".", "_")
    name = name.replace("-", "_").replace(" ", "_")
    # Remove leading underscores and digits
    while name and (name[0].isdigit() or name[0] == '_'):
        name = name[1:]
    return f"res_{name}"


def embed_file(filepath: str, base_dir: str, prefix: str = "") -> tuple:
    """Read a file and return (virtual_path, var_name, byte_array_code)."""
    rel_path = os.path.relpath(filepath, base_dir).replace("\\", "/")
    if prefix:
        rel_path = prefix + "/" + rel_path
    var_name = make_var_name(rel_path)

    with open(filepath, "rb") as f:
        data = f.read()

    # Format as C++ byte array
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals}")

    byte_array = f"static const uint8_t {var_name}_data[] = {{\n"
    byte_array += ",\n".join(lines)
    byte_array += "\n};\n"

    return rel_path, var_name, byte_array, len(data)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <resource_dir> <output_dir> [path_prefix]")
        print(f"Example: {sys.argv[0]} resources/ src/generated/ resources")
        sys.exit(1)

    resource_dir = sys.argv[1]
    output_dir = sys.argv[2]
    prefix = sys.argv[3] if len(sys.argv) > 3 else ""

    if not os.path.isdir(resource_dir):
        print(f"Error: Resource directory not found: {resource_dir}")
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    # Collect all resource files
    files = []
    for root, dirs, filenames in os.walk(resource_dir):
        for fname in filenames:
            fpath = os.path.join(root, fname)
            files.append(fpath)

    if not files:
        print(f"No files found in {resource_dir}")
        sys.exit(0)

    files.sort()

    # Generate .cpp
    cpp_path = os.path.join(output_dir, "embedded_resources.cpp")
    with open(cpp_path, "w", encoding="utf-8") as f:
        f.write(CPP_HEADER)

        # Write byte arrays
        entries = []
        for fpath in files:
            rel_path, var_name, byte_code, size = embed_file(fpath, resource_dir, prefix)
            f.write(f"// {rel_path} ({size} bytes)\n")
            f.write(byte_code)
            entries.append((rel_path, var_name, size))

        # Write registration
        f.write(CPP_FOOTER)
        for rel_path, var_name, size in entries:
            f.write(f'    s_resources["{rel_path}"] = {{{var_name}_data, {size}}};\n')
        f.write(CPP_FOOTER2)

    # Generate .h
    h_path = os.path.join(output_dir, "embedded_resources.h")
    with open(h_path, "w", encoding="utf-8") as f:
        f.write(HEADER)

    total_size = sum(os.path.getsize(f) for f in files)
    print(f"[NUI] Embedded {len(files)} files ({total_size:,} bytes) -> {cpp_path}")


if __name__ == "__main__":
    main()
