#include "core/log.h"
// NUI: ResourceManager implementation
// Tries embedded resources first, then falls back to filesystem.

#include "renderer/resource.h"

#include <cstdio>
#include <fstream>
#include <vector>
#include <map>

// Include generated embedded resources if available
// This header is generated by tools/embed_resources.py
#if __has_include("generated/embedded_resources.h")
#define NUI_HAS_EMBEDDED_RESOURCES 1
#include "generated/embedded_resources.h"
#else
#define NUI_HAS_EMBEDDED_RESOURCES 0
#endif

namespace nui {

void ResourceManager::Initialize() {
#if NUI_HAS_EMBEDDED_RESOURCES
    RegisterEmbeddedResources();
    NUI_LOG("[NUI] Embedded resources registered\n");
#else
    NUI_LOG("[NUI] No embedded resources, using filesystem only\n");
#endif
}

ResourceData ResourceManager::Load(const std::string& path) {
    // Try embedded first
    ResourceData result = LoadEmbedded(path);
    if (result.valid()) return result;

    // Fall back to filesystem
    return LoadFile(path);
}

bool ResourceManager::Exists(const std::string& path) {
    return LoadEmbedded(path).valid() || !GetFilePath(path).empty();
}

std::string ResourceManager::GetFilePath(const std::string& path) {
    // Check if file exists on disk
    std::ifstream f(path, std::ios::binary);
    if (f.good()) return path;
    return {};
}

ResourceData ResourceManager::LoadEmbedded(const std::string& path) {
#if NUI_HAS_EMBEDDED_RESOURCES
    const EmbeddedResource* res = GetEmbeddedResource(path);
    if (res) {
        return {res->data, res->size};
    }
#endif
    return {};
}

ResourceData ResourceManager::LoadFile(const std::string& path) {
    // Cache loaded files to avoid duplicates and leaks
    static std::map<std::string, std::vector<uint8_t>> s_fileCache;

    auto it = s_fileCache.find(path);
    if (it != s_fileCache.end()) {
        return {it->second.data(), it->second.size()};
    }

    std::ifstream file(path, std::ios::binary | std::ios::ate);
    if (!file.is_open()) return {};

    size_t size = static_cast<size_t>(file.tellg());
    file.seekg(0, std::ios::beg);

    auto& buf = s_fileCache[path];
    buf.resize(size);
    file.read(reinterpret_cast<char*>(buf.data()), size);
    return {buf.data(), size};
}

} // namespace nui
